// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hicjqrnxlmbovctfwgya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpY2pxcm54bG1ib3ZjdGZ3Z3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTM3MDcsImV4cCI6MjA2NjI2OTcwN30.GwnAPx2jGt77j4ftt_0BPnVCkxy33DL0EsGlPTTap4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);